name: Reprocess file

on:
  workflow_dispatch:
    inputs:
      s3Path:
        description: "The s3KeyPath for file you need to retrigger"
        required: true
      environment:
        description: "Select environment (e.g., production, staging)"
        required: true
        type: environment

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Configure AWS credentials from OpenID Connect (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies using pnpm
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: Reprocess file
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          S3_PATH: ${{ github.event.inputs.s3Path }}
          QUEUE_URL: ${{ secrets.QUEUE_URL }}
        run: |
          pnpm run main
